<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Topas</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?=.+=.+)</string>
			<key>end</key>
			<string>^[(?=.*=)\s]</string>
			<key>name</key>
			<string>meta.declaration.topas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#data_type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>.*</string>
			<key>name</key>
			<string>comment.block.topas</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>boolean</key>
		<dict>
			<key>match</key>
			<string>"(?i:(true|false|t|f|1|0))"</string>
			<key>name</key>
			<string>constant.language.topas</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.topas</string>
		</dict>
		<key>data_type</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.topas</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([bidus]v?c?):</string>
			<key>name</key>
			<string>meta.topas</string>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>(?i:(includefile|inheritedvalue))</string>
			<key>name</key>
			<string>keyword.other.topas</string>
		</dict>
		<key>numeric</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w)[-+]?(\d+(\.\d*)?|\.\d+)([eE][-+]?\d+)?</string>
			<key>name</key>
			<string>constant.numeric.topas</string>
		</dict>
		<key>operator</key>
		<dict>
			<key>match</key>
			<string>[=+*-]</string>
			<key>name</key>
			<string>keyword.operator.topas</string>
		</dict>
		<key>parameter</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section.topas</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.topas</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:(ma|el|is|ge|gr|ph|so|sc|tf|ts|vr)[/\w]*/)([\w]+)</string>
			<key>name</key>
			<string>variable.parameter.topas</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.topas</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.topas</string>
	<key>uuid</key>
	<string>65752c66-cd2c-4af4-8afd-c4803161a801</string>
</dict>
</plist>
